Repository links-lang/links, pull requests merged in 2018-06, with the labels that each got.

#349 Resolves issue #341 "No way to disable OCaml stack traces when Links fails"
  core/errors.ml
  core/notfound.ml
  core/utility.ml
Labels: bug, enhancement

#348 Change the semantics of print
  core/lexer.mll
  core/lib.ml
  core/utility.ml
  examples/AIPL14/SMTP/Problem1.links
  examples/AIPL14/SMTP/Problem2.links
  examples/AIPL14/SMTP/Problem3.links
  examples/AIPL14/SMTP/Problem4.links
  examples/AIPL14/Solutions/Problem1.links
  examples/AIPL14/Solutions/Problem2.links
  examples/AIPL14/Solutions/Problem3.links
  examples/AIPL14/Solutions/Problem4.links
  examples/distribution/clientProcessOnServer2.links
  examples/distribution/serverToClient.links
  examples/distribution/serverToClient2.links
  examples/handlers/aop.links
  examples/handlers/aop2.links
  examples/handlers/async.links
  examples/handlers/choice.links
  examples/handlers/concurrency.links
  examples/handlers/deep_state.links
  examples/handlers/exceptions.links
  examples/handlers/fringe.links
  examples/handlers/hello_world.links
  examples/handlers/monadic_reflection.links
  examples/handlers/nim-problem.links
  examples/handlers/nim.links
  examples/handlers/number_games.links
  examples/handlers/pi.links
  examples/handlers/pipes.links
  examples/handlers/sat.links
  examples/handlers/state_web.links
  examples/serverClientProcess.links
  examples/serverHandler.links
  examples/sessions/Elvina/IRC.links
  examples/sessions/Elvina/IRC_Test.links
  examples/sessions/Elvina/SMTP_Real_CP.links
  examples/sessions/chatserver/chatClient.links
  examples/sessions/fusegg.links
  examples/sessions/smtp-dummy.links
  examples/sessions/smtp-end.links
  examples/sessions/smtp-factored-more.links
  examples/sessions/smtp-factored.links
  examples/sessions/smtp-formlet.links
  examples/sessions/smtp.links
  prelude.links
Labels: enhancement

#346 More lazy unification errors
  core/typeSugar.ml
Labels: enhancement

#351 Allow open variants in handler case patterns
  core/typeSugar.ml
  core/utility.ml
  tests/handlers.tests
Labels: bug

#356 Fixing #345: Inconsistent Regex behaviour
  lib/js/jslib.js
Labels: bug, enhancement

#357 Delete regex.js
  core/irtojs.ml
  lib/js/jbuild
  lib/js/jslib.js
  lib/js/regex.js
Labels: cleanup, enhancement

#355 Towards de-cycling recursive types + type-checking the IR
  bin/links.ml
  core/backend.ml
  core/buildTables.ml
  core/closures.ml
  core/ir.ml
  core/ir.mli
  core/irTraversals.ml
  core/irTraversals.mli
  core/types.ml
  core/types.mli
  core/var.ml
Labels: enhancement
