Repository links-lang/links, pull requests merged in 2018-07, with the labels that each got.

#361 Resolves links-lang/links#360
  core/typeSugar.ml
  tests/annotations.tests
Labels: bug

#367 Migrates from jbuilder to dune.
  .travis.yml
  Makefile
  bin/dune
  bin/jbuild
  core/dune
  core/jbuild
  database/dune
  database/jbuild
  database/pg-driver/dune
  database/pg-driver/jbuild
  dune
  dune-project
  lib/dune
  lib/jbuild
  lib/js/dune
  lib/js/jbuild
  lib/stdlib/dune
  lib/stdlib/jbuild
  links-postgresql.opam
  links.opam
Labels: workflow

#372 Remove tofix subfolder from examples
  examples/tofix/chat.cgi
  examples/tofix/dom-send.links
  examples/tofix/formlet-idiom.links
  examples/tofix/formlets-demo.links
  examples/tofix/funtests.links
  examples/tofix/gcide.links
  examples/tofix/interactive.links
  examples/tofix/links-suggest.links
  examples/tofix/linkswine/index.cgi
  examples/tofix/linkswine/winestore.data
  examples/tofix/linkswine/winestore.data.pg
  examples/tofix/login-contin.links
  examples/tofix/login-recursive.links
  examples/tofix/mandeltest.links
  examples/tofix/nbe.links
  examples/tofix/new-dom-api.links
  examples/tofix/regex.links
  examples/tofix/sleep.links
  examples/tofix/token-ring-client.links
  examples/tofix/token-ring-server.links
  examples/tofix/web-include-test.links
  examples/tofix/xml-access.links
  examples/tofix/xml_typing.links
Labels: cleanup

#371 Return only dom elements instead of whitespaces
  lib/js/jslib.js
Labels: bug, cleanup, enhancement

#376 Fixes buggy implementation of getValue in jslib
  lib/js/jslib.js
Labels: bug
