Repository links-lang/links, pull requests merged in 2019-06, with the labels that each got.

#625 Syntactic sugar for effect variables in higher-order functions
  core/basicsettings.ml
  core/desugarDatatypes.ml
  core/lib.ml
  core/parser.mly
  core/sugarConstructors.ml
  core/sugarConstructorsIntf.ml
  core/types.ml
  core/types.mli
  prelude.links
  tests/functions.tests
  tests/functions.tests.effect_sugar.config
Labels: enhancement

#626 Cleanup of SQL generation in query.ml
  core/evalir.ml
  core/query/evalNestedQuery.ml
  core/query/evalQuery.ml
  core/query/evalQuery.mli
  core/query/query.ml
  core/query/query.mli
  core/query/sql.ml
Labels: cleanup

#628 [Azure Pipelines] Extend the test matrix
  azure-pipelines.yml
  tools/configure-postgresql
Labels: enhancement

#630 Upgrade Websocket dependency
  core/dune
  core/lib.ml
  core/lib.mli
  core/proc.ml
  core/proc.mli
  core/utility.ml
  core/webserver.ml
  links.opam
Labels: cleanup, enhancement

#633 [CI] macOS database installation regression
  azure-pipelines.yml
Labels: enhancement

#632 Refactor the loader for database drivers.
  core/basicsettings.ml
  core/databaseDriver.ml
  core/databaseDriver.mli
  core/dbDriverDynload.ml
  core/utility.ml
  core/value.ml
Labels: enhancement

#631 Desugar datatype cleanup
  core/basicsettings.ml
  core/commonTypes.ml
  core/desugarDatatypes.ml
  core/parser.mly
  core/sugartypes.ml
  tests/desugar_datatypes.tests
  tests/desugar_datatypes.tests.infer_kinds.config
  tests/desugar_datatypes/nestedQuantifiers1.links
  tests/desugar_datatypes/nestedQuantifiers2.links
  tests/desugar_datatypes/nestedTypename.links
  tests/desugar_datatypes/shadowKinds.links
  tests/mutual.tests
  tests/mutual/sharedTyvar.links
Labels: bug, cleanup, enhancement

#642 Allow primes/single-quotes in identifier names
  core/errors.ml
  core/errors.mli
  core/js.ml
  core/lexer.mll
  core/typeSugar.ml
  links-mode.el
  tests/alien.tests
  tests/bindings.tests
  tests/variants.tests
Labels: enhancement

#644 [CI] Travis: Upgrade Trusty -> Xenial
  .travis.yml
Labels: enhancement

#647 Nominal modules.
  core/chaser.ml
  core/desugarAlienBlocks.ml
  core/desugarModules.ml
  core/moduleUtils.ml
  core/parser.mly
  core/sugarConstructors.ml
  core/sugarConstructorsIntf.ml
  core/sugarTraversals.ml
  core/sugartypes.ml
Labels: cleanup, enhancement

#646 Abstract binders
  core/chaser.ml
  core/compilePatterns.ml
  core/desugarCP.ml
  core/desugarFuns.ml
  core/desugarInners.ml
  core/desugarSessionExceptions.ml
  core/dumpTypes.ml
  core/sugarConstructors.ml
  core/sugarTraversals.ml
  core/sugartoir.ml
  core/sugartypes.ml
  core/transformSugar.ml
  core/typeSugar.ml
  core/types.ml
Labels: enhancement

#648 Removes the `dumpTypes` function from the Links standard library.
  bin/driver.ml
  core/dumpTypes.ml
  core/lib.ml
  core/lib.mli
Labels: cleanup, enhancement, technical-debt

#653 Disable dune implicit-transitive-deps.
  bin/dune
  core/dune
  dune-project
  lens/dune
  links.opam
  tests/unit/dune
  tests/unit/unitTestsLensCommon.ml
  tests/unit/unitTestsLensPerformance.ml
  tests/unit/unitTestsLensSetOperations.ml
Labels: cleanup, enhancement
