Repository links-lang/links, pull requests merged in 2019-08, with the labels that each got.

#709 Display an alert if `jslib` fails to load.
  core/page.ml
  lib/js/jslib.js
Labels: enhancement

#712 Specify the compatible version range of `dune`.
  links-mysql.opam.unsupported
  links-postgresql.opam
  links-sqlite3.opam
Labels: cleanup, confusion

#713 Remove the option `realpages`.
  core/basicsettings.ml
  core/webif.ml
  core/webif.mli
Labels: cleanup

#714 Untag `dune` as a build-time dependency.
  links-mysql.opam.unsupported
  links-postgresql.opam
  links-sqlite3.opam
  links.opam
Labels: cleanup

#715 Decouple IR type structure simplifications from IR type checking.
  core/backend.ml
  core/basicsettings.ml
Labels: bug, cleanup, enhancement

#722 Restore the constancy between `run-tests` and `test-harness`.
  run-tests
  test-harness
Labels: bug, confusion

#718 Decouple IR type structure simplifications from IR type checking.
  core/backend.ml
  core/basicsettings.ml
  tests/typed_ir.tests.config
Labels: bug, cleanup, enhancement

#730 Prepare for Lwt 5.0.0.
  core/proc.ml
Labels: enhancement

#724 Endow testscripts with an optional header section.
  test-harness
  tests/freezeml.tests
  tests/typed_ir.tests
Labels: enhancement

#725 Improve support for `Body and `Alias in IR type equality checks
  core/irCheck.ml
Labels: bug, cleanup
