Repository links-lang/links, pull requests merged in 2019-02, with the labels that each got.

#479 Updates the development and release build profiles.
  Makefile
  bin/dune
  core/lexer.mll
  core/performance.ml
  core/xmlLexer.mll
  dune
Labels: bug, cleanup, enhancement

#472 Query SQL refactoring
  core/evalir.ml
  core/query/evalNestedQuery.ml
  core/query/evalQuery.ml
  core/query/evalQuery.mli
  core/query/query.ml
  core/query/query.mli
  core/query/sql.ml
Labels: cleanup

#485 The obvious thing works to allow qualified type constructor applications
  core/parser.mly
Labels: bug, cleanup, enhancement

#402 Move manual install/remove steps to dune
  .gitignore
  dune
  install.inc
  links.opam
  preinstall/dune
  preinstall/preinstall.ml
Labels: cleanup, enhancement
