Repository links-lang/links, pull requests merged in 2019-05, with the labels that each got.

#534 Generate type applications for desugared anonymous functions
  core/desugarFuns.ml
  core/transformSugar.ml
  tests/empty_prelude.links
  tests/typed_ir.tests
  tests/typed_ir.tests.config
Labels: IR Typing, bug

#602 Desugar modules properly
  bin/repl.ml
  core/chaser.ml
  core/chaser.mli
  core/desugarAlienBlocks.ml
  core/desugarAlienBlocks.mli
  core/desugarModules.ml
  core/desugarModules.mli
  core/errors.ml
  core/errors.mli
  core/frontend.ml
  core/js.ml
  core/module_hacks.ml
  core/types.ml
  tests/binaryTrees.tests
  tests/modules.tests
  tests/modules/alien_blocks_dependency.links
  tests/modules/alien_blocks_importer.links
  tests/modules/boundary_peek.links
  tests/modules/import0.links
  tests/modules/import1.links
  tests/modules/import2.links
  tests/modules/labels0.links
  tests/modules/labels1.links
  tests/modules/type-scoping-bad1.links
  tests/modules/type-scoping1.links
  tests/modules/type-scoping2.links
  tests/modules/type-scoping3.links
  tests/modules/type-scoping4.links
  tests/modules/type-scoping5.links
  tests/modules/type-scoping6.links
Labels: cleanup, enhancement

#607 Switch examples to use import
  core/chaser.ml
  core/desugarModules.ml
  core/parser.mly
  core/sugarConstructors.ml
  core/sugarConstructorsIntf.ml
  core/sugarTraversals.ml
  core/sugartypes.ml
  examples/handlers/tests.links
  examples/sessions/chatserver/chatClient.links
  examples/sessions/chatserver/chatServer.links
  examples/sessions/mind/mindClient.links
  examples/sessions/mind/mindServer.links
  examples/webserver/examples-nodb.links
  examples/webserver/examples.links
  links-mode.el
Labels: cleanup

#608 [Handlers] Paying off technical debt
  core/desugarHandlers.ml
  core/desugarHandlers.mli
  core/desugarModules.ml
  core/desugarModules.mli
  core/experimentalExtensions.ml
  core/frontend.ml
  core/lexer.mll
  core/parser.mly
  core/sugarConstructors.ml
  core/sugarConstructorsIntf.ml
  core/sugarTraversals.ml
  core/sugarTraversals.mli
  core/sugartoir.ml
  core/sugartypes.ml
  core/transformSugar.ml
  core/transformSugar.mli
  core/typeSugar.ml
  examples/handlers/deep_pipes.links
  examples/handlers/identity.links
  examples/handlers/pipes.links
  examples/handlers/shallow_pipes.links
  examples/handlers/tests.links
  links-mode.el
  tests/handlers.tests
Labels: cleanup

#609 Semantics of `open` is not `include`.
  core/desugarModules.ml
  tests/modules.tests
  tests/modules/open_is_not_include0.links
  tests/modules/open_is_not_include1.links
  tests/modules/open_is_not_include2.links
Labels: bug, cleanup

#610 Improve the REPL efficacy when using modules.
  bin/repl.ml
  core/basicsettings.ml
  core/desugarModules.ml
Labels: cleanup, enhancement

#612 Disallow alien blocks below top-level
  core/parser.mly
  tests/alien.tests
Labels: bug, cleanup

#614 [Handlers] Generalise parameterised handlers.
  core/compilePatterns.ml
  core/parser.mly
  core/sugarConstructorsIntf.ml
  core/sugarTraversals.ml
  core/sugartoir.ml
  core/sugartypes.ml
  core/transformSugar.ml
  core/typeSugar.ml
  examples/handlers/light_switch.links
  examples/handlers/nim-webversion.links
  examples/handlers/number_games.links
  examples/handlers/pi.links
  examples/handlers/racing-lines.links
  examples/handlers/sat.links
  examples/handlers/sierpinski-triangle.links
  examples/handlers/transaction.links
  tests/handlers.tests
Labels: bug, cleanup, enhancement

#615 Removes `rewrite.ml` which is unused.
  core/rewrite.ml
Labels: cleanup

#617 Localise extension checks.
  core/experimentalExtensions.ml
  core/frontend.ml
  core/typeSugar.ml
Labels: cleanup

#613 Change the semantics of open
  core/chaser.ml
  tests/modules.tests
  tests/modules/alien_blocks_importer.links
  tests/modules/import_via_open0.links
  tests/modules/import_via_open1.links
  tests/modules/moduleA.links
  tests/modules/moduleB.links
  tests/modules/overflow-test/test.links
  tests/stdlibtests/binaryTree/inorder.links
  tests/stdlibtests/binaryTree/postorder.links
  tests/stdlibtests/binaryTree/preorder.links
  tests/stdlibtests/binaryTree/remove1.links
  tests/stdlibtests/binaryTree/remove2.links
Labels: cleanup
