Repository links-lang/links, pull requests merged in 2021-08, with the labels that each got.

#1000 Surface syntax for Presence type arguments.
  core/parser.mly
  core/types.ml
  examples/handlers/racing-lines.links
  examples/handlers/sierpinski-triangle.links
  examples/handlers/transaction.links
  tests/presence_type_arg.config
  tests/presence_type_arg.tests
  tests/presence_type_arg_typename.links
  tools/rules/test_files_registered.py
Labels: cleanup, enhancement, question

#936 Heterogeneous queries and delateralization
  core/commonTypes.ml
  core/database.ml
  core/database.mli
  core/evalir.ml
  core/lib.ml
  core/parser.mly
  core/query/delateralize.ml
  core/query/delateralize.mli
  core/query/evalMixingQuery.ml
  core/query/evalNestedQuery.ml
  core/query/evalQuery.ml
  core/query/mixingQuery.ml
  core/query/mixingQuery.mli
  core/query/query.ml
  core/query/query.mli
  core/query/queryLang.ml
  core/query/queryLang.mli
  core/query/sql.ml
  core/typeSugar.ml
  core/utility.ml
  prelude.links
Labels: enhancement

#1028 Introduce DateTime type
  CHANGES.md
  core/commonTypes.ml
  core/database.ml
  core/dune
  core/evalir.ml
  core/irTraversals.ml
  core/irtojs.ml
  core/json.ml
  core/lens_value_conv.ml
  core/lib.ml
  core/parser.mly
  core/query/query.ml
  core/query/query.mli
  core/query/queryLang.ml
  core/query/queryLang.mli
  core/query/sql.ml
  core/serialisation.ml
  core/sugarTraversals.ml
  core/sugarTraversals.mli
  core/timestampLexer.mll
  core/timestampParser.mly
  core/transformSugar.ml
  core/types.ml
  core/types.mli
  core/utility.ml
  core/value.ml
  core/value.mli
  database/pg-driver/pg_database.ml
  examples/mvu/dates.links
  lib/js/jslib.js
  links.opam
  prelude.links
  tests/datetime.tests
  tests/dos-newlines.links
  tests/shredding/dates.links
  tests/shredding/dates.sql
  tests/shredding/testsuite.json
  tests/typecheck_examples.tests
Labels: enhancement

#1006 Effect Sugar: Act 1: Enter the Printer
  core/parser.mly
  core/typeUtils.ml
  core/types.ml
  core/types.mli
  core/utility.ml
  tests/effect_sugar.tests
Labels: bug, enhancement

#1038 Effect Sugar: Fix operations not propagating from within aliases
  core/desugarEffects.ml
Labels: bug, enhancement

#1032 Effect Sugar: Sharing of Implicit Effect Variables
  core/desugarEffects.ml
  core/types.ml
  core/types.mli
  examples/handlers/coins.links
  examples/handlers/fringe.links
  examples/handlers/shallow_state.links
  examples/handlers/shiftreset.links
  tests/effect_sugar.tests
Labels: enhancement

#1043 Update CHANGES.md with recursive rows, roundtrip printer and effect sugar
  CHANGES.md
Labels: documentation
