Repository links-lang/links, pull requests merged in 2021-07, with the labels that each got.

#982 New round-tripping type pretty printer
  bin/repl.ml
  core/desugarEffects.ml
  core/typeSugar.ml
  core/typeUtils.ml
  core/types.ml
  core/types.mli
  tests/continuations.tests
  tests/desugar_datatypes.tests
  tests/handlers.tests
  tests/parser.tests
  tests/recheck_frontend_transformations.config
  tests/roundtrip/record_update.links
  tests/roundtrippable_types.tests
  tests/type_print.tests
  tests/variants.tests
Labels: bug, cleanup, enhancement

#1001 Wrap `@load` in an error handler.
  bin/repl.ml
  core/desugarEffects.ml
Labels: bug, cleanup

#1012 Default HTTP response when process throws `Aborted`.
  core/webif.ml
Labels: bug, cleanup

#1019 Coping with deeply nested literal JSON objects.
  core/irtojs.ml
Labels: enhancement

#1022 Resolve arguments inside call packages.
  lib/js/jslib.js
Labels: bug

#1025 Do not print backtrace on "unknown directive"
  bin/repl.ml
Labels: bug, cleanup

#1026 Fix nested effect rows printing incorrectly
  core/types.ml
  tests/roundtrippable_types.tests
Labels: bug

#1023 Robust resolution of deeply nested server values.
  lib/js/jslib.js
Labels: bug, cleanup, enhancement
